# Declarative Act registration. Author: Al Amin Ahamed.

slug: code-of-civil-procedure-1908
short_name: Code of Civil Procedure 1908
full_name_en: The Code of Civil Procedure, 1908
full_name_bn: দেওয়ানি কার্যবিধি, ১৯০৮
act_number: V
act_year: 1908
ministry: Ministry of Law, Justice and Parliamentary Affairs
status: in_force

sources:
  - language: bn
    source_url: http://bdlaws.minlaw.gov.bd/act-86.html
  - language: en
    source_url: http://bdlaws.minlaw.gov.bd/act-86.html?lang=en
